import { Card } from '@/types';

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

export const SAMPLE_CARDS: Card[] = [
  {
    id: 'sample-1',
    player: 'Patrick Mahomes',
    year: 2017,
    brand: 'Panini Prizm',
    cardNumber: '269',
    variation: 'Rookie Card Silver Prizm',
    condition: 'PSA 10',
    purchasePrice: 450,
    currentValue: 620,
    sport: 'Football',
    addedAt: daysAgo(90),
  },
  {
    id: 'sample-2',
    player: 'Luka Doncic',
    year: 2018,
    brand: 'Panini Prizm',
    cardNumber: '280',
    variation: 'Rookie Card Silver Prizm',
    condition: 'PSA 9',
    purchasePrice: 180,
    currentValue: 210,
    sport: 'Basketball',
    addedAt: daysAgo(60),
  },
  {
    id: 'sample-3',
    player: 'Shohei Ohtani',
    year: 2018,
    brand: 'Topps Chrome',
    cardNumber: '150',
    variation: 'Rookie Card',
    condition: 'PSA 10',
    purchasePrice: 120,
    currentValue: 890,
    sport: 'Baseball',
    addedAt: daysAgo(45),
  },
  {
    id: 'sample-4',
    player: 'Victor Wembanyama',
    year: 2023,
    brand: 'Panini Prizm',
    cardNumber: '301',
    variation: 'Rookie Card Silver Prizm',
    condition: 'Raw',
    purchasePrice: 85,
    currentValue: 165,
    sport: 'Basketball',
    addedAt: daysAgo(20),
  },
  {
    id: 'sample-5',
    player: 'Julio Rodriguez',
    year: 2022,
    brand: 'Topps Chrome',
    cardNumber: '33',
    variation: 'Rookie Card Refractor',
    condition: 'PSA 10',
    purchasePrice: 95,
    currentValue: 72,
    sport: 'Baseball',
    addedAt: daysAgo(30),
  },
];
