'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';
import { Brain, RefreshCw, ScanLine, AlertCircle, BarChart2, Star, Layers } from 'lucide-react';
import { useStore } from '@/lib/store';
import SignalCard from '@/components/intelligence/SignalCard';
import SignalSkeleton from '@/components/intelligence/SignalSkeleton';
import { CardSignal, SignalType } from '@/types';

const FILTER_OPTS: Array<{ label: string; value: SignalType | 'ALL' }> = [
  { label: 'All',  value: 'ALL'  },
  { label: 'Buy',  value: 'BUY'  },
  { label: 'Sell', value: 'SELL' },
  { label: 'Hold', value: 'HOLD' },
];

const DIMENSIONS = [
  {
    icon: BarChart2,
    label: 'Price Trend Analysis',
    color: 'text-electric',
    bg: 'border-electric/20 bg-electric/[0.07]',
  },
  {
    icon: Star,
    label: 'Player Performance',
    color: 'text-gold-400',
    bg: 'border-[rgba(245,200,66,0.2)] bg-[rgba(245,200,66,0.07)]',
  },
  {
    icon: Layers,
    label: 'Scarcity & Grade',
    color: 'text-purple-400',
    bg: 'border-purple-500/20 bg-purple-500/[0.07]',
  },
];

interface StreamState {
  signal?: SignalType;
  confidence?: number;
  summary?: string;
  priceTarget?: number;
  timeframe?: string;
  priceTrend?: string;
  playerContext?: string;
  scarcityNote?: string;
  activeField?: 'priceTrend' | 'playerContext' | 'scarcityNote';
  phase: 'waiting' | 'verdict' | 'streaming';
}

type SSEEvent =
  | { type: 'verdict'; signal: SignalType; confidence: number; summary: string; priceTarget?: number; timeframe?: string }
  | { type: 'chunk'; field: 'priceTrend' | 'playerContext' | 'scarcityNote'; text: string }
  | { type: 'done'; signal: CardSignal; fromCache?: boolean }
  | { type: 'error'; message: string };

const SIGNAL_COUNT_STYLES = {
  BUY:  { text: 'text-emerald-400', ring: 'ring-emerald-500/40', bg: 'bg-emerald-500/10 hover:bg-emerald-500/15' },
  SELL: { text: 'text-red-400',     ring: 'ring-red-500/40',     bg: 'bg-red-500/10 hover:bg-red-500/15'       },
  HOLD: { text: 'text-amber-400',   ring: 'ring-amber-500/40',   bg: 'bg-amber-500/10 hover:bg-amber-500/15'   },
};

export default function IntelligencePage() {
  const { state, dispatch } = useStore();
  const { cards, signals }  = state;

  const [generatingIds, setGeneratingIds] = useState<Set<string>>(new Set());
  const [streamMap, setStreamMap] = useState<Map<string, StreamState>>(new Map());
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<SignalType | 'ALL'>('ALL');
  const autoGeneratedRef = useRef(false);

  const isGenerating  = generatingIds.size > 0;
  const completedCount = isGenerating ? cards.length - generatingIds.size : 0;

  const handleSSEEvent = useCallback(
    (cardId: string, event: SSEEvent) => {
      switch (event.type) {
        case 'verdict':
          setStreamMap((prev) => new Map(prev).set(cardId, {
            signal: event.signal, confidence: event.confidence,
            summary: event.summary, priceTarget: event.priceTarget,
            timeframe: event.timeframe, phase: 'verdict',
          }));
          break;
        case 'chunk':
          setStreamMap((prev) => {
            const existing = prev.get(cardId) ?? { phase: 'streaming' as const };
            const asRecord = existing as unknown as Record<string, string>;
            return new Map(prev).set(cardId, {
              ...existing,
              [event.field]: (asRecord[event.field] ?? '') + event.text,
              activeField: event.field,
              phase: 'streaming',
            });
          });
          break;
        case 'done':
          setStreamMap((prev) => { const n = new Map(prev); n.delete(cardId); return n; });
          dispatch({ type: 'ADD_SIGNAL', signal: event.signal });
          setGeneratingIds((prev) => { const n = new Set(prev); n.delete(cardId); return n; });
          break;
        case 'error':
          setStreamMap((prev) => { const n = new Map(prev); n.delete(cardId); return n; });
          setGeneratingIds((prev) => { const n = new Set(prev); n.delete(cardId); return n; });
          break;
      }
    },
    [dispatch]
  );

  const generateSignals = useCallback(async () => {
    if (cards.length === 0) return;
    setError(null);
    setStreamMap(new Map());
    dispatch({ type: 'SET_SIGNALS', signals: [] });
    setGeneratingIds(new Set(cards.map((c) => c.id)));
    let failCount = 0;

    await Promise.allSettled(
      cards.map(async (card) => {
        try {
          const res = await fetch('/api/signals', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ card }),
          });
          if (!res.body) throw new Error('No response body');
          const reader = res.body.getReader();
          const decoder = new TextDecoder();
          let buf = '';
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buf += decoder.decode(value, { stream: true });
            const parts = buf.split('\n\n');
            buf = parts.pop() ?? '';
            for (const part of parts) {
              const line = part.trim();
              if (!line.startsWith('data: ')) continue;
              try { handleSSEEvent(card.id, JSON.parse(line.slice(6))); } catch { /* skip */ }
            }
          }
        } catch {
          failCount++;
          setGeneratingIds((prev) => { const n = new Set(prev); n.delete(card.id); return n; });
        }
      })
    );

    if (failCount > 0) setError(`Failed to analyze ${failCount} card${failCount !== 1 ? 's' : ''}`);
  }, [cards, dispatch, handleSSEEvent]);

  useEffect(() => {
    if (cards.length > 0 && signals.length === 0 && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateSignals();
    }
  }, [cards.length, signals.length, generateSignals]);

  const filtered = filter === 'ALL' ? signals : signals.filter((s) => s.signal === filter);
  const counts   = {
    BUY:  signals.filter((s) => s.signal === 'BUY').length,
    SELL: signals.filter((s) => s.signal === 'SELL').length,
    HOLD: signals.filter((s) => s.signal === 'HOLD').length,
  };

  function streamToSignal(cardId: string, player: string, s: StreamState): CardSignal {
    return {
      cardId, player,
      signal: s.signal ?? 'HOLD',
      confidence: s.confidence ?? 0,
      summary: s.summary ?? '',
      priceTrend: s.priceTrend ?? '',
      playerContext: s.playerContext ?? '',
      scarcityNote: s.scarcityNote ?? '',
      priceTarget: s.priceTarget,
      timeframe: s.timeframe,
      generatedAt: new Date().toISOString(),
    };
  }

  if (cards.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center fade-in-up">
        <div className="w-16 h-16 border border-[rgba(245,200,66,0.28)] bg-[rgba(245,200,66,0.07)] flex items-center justify-center mb-5 rounded-xl">
          <Brain className="text-gold-400" size={28} strokeWidth={1.5} />
        </div>
        <h1 className="font-card text-5xl uppercase tracking-widest text-white mb-2">No cards to analyze</h1>
        <p className="text-slate-400 mb-8 font-sans max-w-sm leading-relaxed">
          Add cards to your portfolio to get AI-powered market signals.
        </p>
        <Link
          href="/scan"
          className="btn-gold inline-flex items-center gap-2 px-6 py-3 font-black text-sm uppercase tracking-widest"
        >
          <ScanLine size={16} />Scan a Card
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6 fade-in-up">

      {/* ── Header ───────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="section-accent font-card text-5xl uppercase tracking-widest text-white">
            Market Intelligence
          </h1>
          <p className="text-slate-500 text-sm mt-2 font-sans max-w-lg leading-relaxed">
            Three-dimensional AI analysis across price trends, player performance, and card scarcity
          </p>
        </div>
        <button
          onClick={generateSignals}
          disabled={isGenerating}
          className="btn-gold flex items-center gap-2 px-5 py-2.5 font-black text-xs uppercase tracking-widest flex-shrink-0"
        >
          <RefreshCw size={13} className={isGenerating ? 'animate-spin' : ''} />
          {isGenerating ? 'Analyzing...' : 'Refresh'}
        </button>
      </div>

      {/* ── Dimension legend ─────────────────────────────────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {DIMENSIONS.map(({ icon: Icon, label, color, bg }) => (
          <div key={label} className={`border rounded-md px-4 py-3.5 flex items-center gap-3 ${bg}`}>
            <Icon size={14} className={color} strokeWidth={2} />
            <span className={`text-[10px] font-black uppercase tracking-widest font-display ${color}`}>{label}</span>
          </div>
        ))}
      </div>

      {/* ── Error ────────────────────────────────────────────────────── */}
      {error && (
        <div className="flex items-center gap-3 bg-red-500/10 border border-red-500/25 rounded-md p-4 text-red-400 text-sm font-sans">
          <AlertCircle size={16} className="flex-shrink-0" />
          {error}
        </div>
      )}

      {/* ── Live generation view ─────────────────────────────────────── */}
      {isGenerating && (
        <div className="space-y-4">
          <div className="chrome-panel px-6 py-5">
            <div className="flex items-center justify-between mb-3">
              <p className="text-white text-sm font-display font-black uppercase tracking-widest">
                Generating market intelligence
              </p>
              <span className="text-electric text-xs font-display font-black uppercase tracking-widest tabular-nums">
                {completedCount} / {cards.length}
              </span>
            </div>
            <div className="w-full h-1.5 bg-[#0A1628] rounded-full overflow-hidden">
              <div
                className="h-full rounded-full transition-all duration-500"
                style={{
                  width: cards.length ? `${(completedCount / cards.length) * 100}%` : '0%',
                  background: 'linear-gradient(90deg, #F5C842, #00D4FF)',
                }}
              />
            </div>
          </div>

          {cards.map((card) => {
            const done      = signals.find((s) => s.cardId === card.id);
            const streaming = streamMap.get(card.id);
            if (done) return <SignalCard key={card.id} signal={done} />;
            if (streaming && streaming.phase !== 'waiting') {
              return (
                <SignalCard
                  key={card.id}
                  signal={streamToSignal(card.id, card.player, streaming)}
                  streaming
                  activeField={streaming.activeField}
                />
              );
            }
            return <SignalSkeleton key={card.id} player={card.player} />;
          })}
        </div>
      )}

      {/* ── Completed view ───────────────────────────────────────────── */}
      {!isGenerating && signals.length > 0 && (
        <>
          {/* Signal summary row */}
          <div className="grid grid-cols-3 gap-4">
            {(['BUY', 'SELL', 'HOLD'] as SignalType[]).map((type) => {
              const s = SIGNAL_COUNT_STYLES[type];
              const active = filter === type;
              return (
                <button
                  key={type}
                  onClick={() => setFilter(filter === type ? 'ALL' : type)}
                  className={[
                    'chrome-panel p-5 text-center transition-all duration-200 cursor-pointer',
                    s.bg,
                    active ? `ring-1 ${s.ring}` : '',
                  ].join(' ')}
                >
                  <p className={`font-card text-4xl tabular-nums ${s.text}`}>{counts[type]}</p>
                  <p className={`text-[10px] font-display font-black uppercase tracking-widest mt-1 ${s.text}`}>{type}</p>
                </button>
              );
            })}
          </div>

          {/* Filter tabs */}
          <div className="flex items-center gap-2 flex-wrap">
            {FILTER_OPTS.map(({ label, value }) => (
              <button
                key={value}
                onClick={() => setFilter(value)}
                className={[
                  'px-4 py-2 rounded-full text-xs font-display font-black uppercase tracking-widest',
                  'transition-all duration-200 cursor-pointer',
                  filter === value
                    ? 'bg-gold-400 text-[#060E1C]'
                    : 'text-chrome-400 hover:text-chrome-100 bg-[#0D1A30] border border-[rgba(192,200,216,0.12)] hover:border-[rgba(192,200,216,0.22)]',
                ].join(' ')}
              >
                {label}
                {value !== 'ALL' && (
                  <span className="ml-1.5 opacity-60 tabular-nums">({counts[value as SignalType]})</span>
                )}
              </button>
            ))}
            <span className="ml-auto text-xs text-chrome-600 font-display uppercase tracking-widest tabular-nums">
              {filtered.length} signal{filtered.length !== 1 ? 's' : ''}
            </span>
          </div>

          <div className="space-y-4">
            {filtered.map((signal) => (
              <SignalCard key={signal.cardId} signal={signal} />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
