'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';
import { Brain, RefreshCw, ScanLine, AlertCircle, BarChart2, Star, Layers } from 'lucide-react';
import { useStore } from '@/lib/store';
import SignalCard from '@/components/intelligence/SignalCard';
import SignalSkeleton from '@/components/intelligence/SignalSkeleton';
import { CardSignal, SignalType } from '@/types';

const FILTER_OPTS: Array<{ label: string; value: SignalType | 'ALL' }> = [
  { label: 'All', value: 'ALL' },
  { label: 'Buy', value: 'BUY' },
  { label: 'Sell', value: 'SELL' },
  { label: 'Hold', value: 'HOLD' },
];

const DIMENSIONS = [
  { icon: BarChart2, label: 'Price Trend Analysis', color: 'text-blue-400', bg: 'bg-blue-500/10 border-blue-500/20' },
  { icon: Star, label: 'Player Performance', color: 'text-gold-400', bg: 'bg-gold-400/10 border-[rgba(245,200,66,0.2)]' },
  { icon: Layers, label: 'Scarcity & Grade', color: 'text-purple-400', bg: 'bg-purple-500/10 border-purple-500/20' },
];

// Local type for in-progress streaming state (not persisted to store)
interface StreamState {
  signal?: SignalType;
  confidence?: number;
  summary?: string;
  priceTarget?: number;
  timeframe?: string;
  priceTrend?: string;
  playerContext?: string;
  scarcityNote?: string;
  activeField?: 'priceTrend' | 'playerContext' | 'scarcityNote';
  phase: 'waiting' | 'verdict' | 'streaming';
}

type SSEEvent =
  | { type: 'verdict'; signal: SignalType; confidence: number; summary: string; priceTarget?: number; timeframe?: string }
  | { type: 'chunk'; field: 'priceTrend' | 'playerContext' | 'scarcityNote'; text: string }
  | { type: 'done'; signal: CardSignal; fromCache?: boolean }
  | { type: 'error'; message: string };

export default function IntelligencePage() {
  const { state, dispatch } = useStore();
  const { cards, signals } = state;

  const [generatingIds, setGeneratingIds] = useState<Set<string>>(new Set());
  const [streamMap, setStreamMap] = useState<Map<string, StreamState>>(new Map());
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<SignalType | 'ALL'>('ALL');
  const autoGeneratedRef = useRef(false);

  const isGenerating = generatingIds.size > 0;
  const completedCount = isGenerating ? cards.length - generatingIds.size : 0;

  const handleSSEEvent = useCallback(
    (cardId: string, event: SSEEvent) => {
      switch (event.type) {
        case 'verdict':
          setStreamMap((prev) =>
            new Map(prev).set(cardId, {
              signal: event.signal,
              confidence: event.confidence,
              summary: event.summary,
              priceTarget: event.priceTarget,
              timeframe: event.timeframe,
              phase: 'verdict',
            })
          );
          break;

        case 'chunk':
          setStreamMap((prev) => {
            const existing = prev.get(cardId) ?? { phase: 'streaming' as const };
            const asRecord = existing as unknown as Record<string, string>;
            const updated: StreamState = {
              ...existing,
              [event.field]: (asRecord[event.field] ?? '') + event.text,
              activeField: event.field,
              phase: 'streaming',
            };
            return new Map(prev).set(cardId, updated);
          });
          break;

        case 'done':
          setStreamMap((prev) => {
            const next = new Map(prev);
            next.delete(cardId);
            return next;
          });
          dispatch({ type: 'ADD_SIGNAL', signal: event.signal });
          setGeneratingIds((prev) => {
            const next = new Set(prev);
            next.delete(cardId);
            return next;
          });
          break;

        case 'error':
          setStreamMap((prev) => {
            const next = new Map(prev);
            next.delete(cardId);
            return next;
          });
          setGeneratingIds((prev) => {
            const next = new Set(prev);
            next.delete(cardId);
            return next;
          });
          break;
      }
    },
    [dispatch]
  );

  const generateSignals = useCallback(async () => {
    if (cards.length === 0) return;
    setError(null);
    setStreamMap(new Map());
    dispatch({ type: 'SET_SIGNALS', signals: [] });
    setGeneratingIds(new Set(cards.map((c) => c.id)));

    let failCount = 0;

    await Promise.allSettled(
      cards.map(async (card) => {
        try {
          const res = await fetch('/api/signals', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ card }),
          });

          if (!res.body) throw new Error('No response body');

          const reader = res.body.getReader();
          const decoder = new TextDecoder();
          let buf = '';

          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            buf += decoder.decode(value, { stream: true });
            // SSE events are separated by double newline
            const parts = buf.split('\n\n');
            buf = parts.pop() ?? '';

            for (const part of parts) {
              const line = part.trim();
              if (!line.startsWith('data: ')) continue;
              try {
                const event: SSEEvent = JSON.parse(line.slice(6));
                handleSSEEvent(card.id, event);
              } catch {
                // skip malformed event
              }
            }
          }
        } catch {
          failCount++;
          setGeneratingIds((prev) => {
            const next = new Set(prev);
            next.delete(card.id);
            return next;
          });
        }
      })
    );

    if (failCount > 0) {
      setError(`Failed to analyze ${failCount} card${failCount !== 1 ? 's' : ''}`);
    }
  }, [cards, dispatch, handleSSEEvent]);

  useEffect(() => {
    if (cards.length > 0 && signals.length === 0 && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateSignals();
    }
  }, [cards.length, signals.length, generateSignals]);

  const filtered = filter === 'ALL' ? signals : signals.filter((s) => s.signal === filter);
  const counts = {
    BUY: signals.filter((s) => s.signal === 'BUY').length,
    SELL: signals.filter((s) => s.signal === 'SELL').length,
    HOLD: signals.filter((s) => s.signal === 'HOLD').length,
  };

  // Convert a StreamState to a CardSignal shape for rendering
  function streamToSignal(cardId: string, player: string, s: StreamState): CardSignal {
    return {
      cardId,
      player,
      signal: s.signal ?? 'HOLD',
      confidence: s.confidence ?? 0,
      summary: s.summary ?? '',
      priceTrend: s.priceTrend ?? '',
      playerContext: s.playerContext ?? '',
      scarcityNote: s.scarcityNote ?? '',
      priceTarget: s.priceTarget,
      timeframe: s.timeframe,
      generatedAt: new Date().toISOString(),
    };
  }

  if (cards.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <div className="w-16 h-16 border border-[rgba(245,200,66,0.3)] bg-gold-400/10 flex items-center justify-center mb-4 rounded-sm">
          <Brain className="text-gold-400" size={28} />
        </div>
        <h1 className="font-card text-5xl uppercase tracking-widest text-white mb-2">No cards to analyze</h1>
        <p className="text-chrome-400 mb-6 font-display">Add cards to your portfolio to get AI-powered market signals.</p>
        <Link href="/scan" className="btn-gold inline-flex items-center gap-2 px-6 py-3 rounded-sm font-black text-sm uppercase tracking-widest">
          <ScanLine size={16} />Scan a Card
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="section-accent font-card text-5xl uppercase tracking-widest text-white">Market Intelligence</h1>
          <p className="text-chrome-400 text-sm mt-1 font-display">
            Three-dimensional AI analysis across price trends, player performance, and card scarcity
          </p>
        </div>
        <button
          onClick={generateSignals}
          disabled={isGenerating}
          className="btn-gold flex items-center gap-2 px-5 py-2.5 rounded-sm font-black text-xs uppercase tracking-widest disabled:opacity-60 disabled:cursor-not-allowed flex-shrink-0"
        >
          <RefreshCw size={14} className={isGenerating ? 'animate-spin' : ''} />
          {isGenerating ? 'Analyzing...' : 'Refresh'}
        </button>
      </div>

      {/* Dimension legend */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {DIMENSIONS.map(({ icon: Icon, label, color, bg }) => (
          <div key={label} className={`border rounded-sm px-4 py-3 flex items-center gap-3 ${bg}`}>
            <Icon size={14} className={color} />
            <span className={`text-[10px] font-black uppercase tracking-widest ${color}`}>{label}</span>
          </div>
        ))}
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-center gap-3 bg-red-500/10 border border-red-500/30 rounded-sm p-4 text-red-400 text-sm">
          <AlertCircle size={16} className="flex-shrink-0" />
          {error}
        </div>
      )}

      {/* Live generation view — cards appear one by one as each stream completes */}
      {isGenerating && (
        <div className="space-y-4">
          {/* Progress bar */}
          <div className="chrome-panel border border-[rgba(0,212,255,0.15)] px-5 py-4">
            <div className="flex items-center justify-between mb-2.5">
              <p className="text-white text-sm font-display font-black uppercase tracking-widest">Generating market intelligence</p>
              <span className="text-electric text-xs font-display font-black uppercase tracking-widest">
                {completedCount} / {cards.length}
              </span>
            </div>
            <div className="w-full h-1 bg-navy-700 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-electric to-gold-400 rounded-full transition-all duration-500"
                style={{ width: cards.length ? `${(completedCount / cards.length) * 100}%` : '0%' }}
              />
            </div>
          </div>

          {cards.map((card) => {
            const done = signals.find((s) => s.cardId === card.id);
            const streaming = streamMap.get(card.id);

            if (done) {
              return <SignalCard key={card.id} signal={done} />;
            }
            if (streaming && streaming.phase !== 'waiting') {
              return (
                <SignalCard
                  key={card.id}
                  signal={streamToSignal(card.id, card.player, streaming)}
                  streaming
                  activeField={streaming.activeField}
                />
              );
            }
            return <SignalSkeleton key={card.id} player={card.player} />;
          })}
        </div>
      )}

      {/* Completed signals with filter UI */}
      {!isGenerating && signals.length > 0 && (
        <>
          <div className="grid grid-cols-3 gap-px bg-[rgba(0,212,255,0.08)] border border-[rgba(0,212,255,0.12)] chrome-texture">
            {(['BUY', 'SELL', 'HOLD'] as SignalType[]).map((type) => {
              const styles = {
                BUY: 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/15',
                SELL: 'bg-red-500/10 text-red-400 hover:bg-red-500/15',
                HOLD: 'bg-amber-500/10 text-amber-400 hover:bg-amber-500/15',
              };
              const ring = {
                BUY: 'ring-1 ring-emerald-500/50',
                SELL: 'ring-1 ring-red-500/50',
                HOLD: 'ring-1 ring-amber-500/50',
              };
              return (
                <button
                  key={type}
                  onClick={() => setFilter(filter === type ? 'ALL' : type)}
                  className={`p-4 text-center transition-all ${styles[type]} ${filter === type ? ring[type] : ''}`}
                >
                  <p className="font-card text-3xl">{counts[type]}</p>
                  <p className="text-[10px] font-display font-black uppercase tracking-widest mt-0.5">{type}</p>
                </button>
              );
            })}
          </div>

          <div className="flex items-center gap-2">
            {FILTER_OPTS.map(({ label, value }) => (
              <button
                key={value}
                onClick={() => setFilter(value)}
                className={`px-4 py-1.5 rounded-sm text-xs font-display font-black uppercase tracking-widest transition-all ${
                  filter === value
                    ? 'bg-electric text-navy-900'
                    : 'text-chrome-400 hover:text-white bg-navy-700 border border-[rgba(0,212,255,0.12)]'
                }`}
              >
                {label}
                {value !== 'ALL' && <span className="ml-1.5 opacity-60">({counts[value]})</span>}
              </button>
            ))}
            <span className="ml-auto text-xs text-chrome-600 font-display uppercase tracking-widest">
              {filtered.length} signal{filtered.length !== 1 ? 's' : ''}
            </span>
          </div>

          <div className="space-y-4">
            {filtered.map((signal) => (
              <SignalCard key={signal.cardId} signal={signal} />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
